replicaCount: 2

ingress:
  enabled: true
  className: alb
  group: go-ride-staging
  path: /api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

serviceAccount:
  name: go-ride-app

env:
  plain:
    DB_PORT: "5432"
    DB_NAME: go_ride
    DB_SSLMODE: require
    JWT_ISSUER: go-ride-backend
    JWT_AUDIENCE: go-ride-clients
    JWT_DRIVER_AUDIENCE: go-ride-drivers
  secretRefs: []

secretsManager:
  enabled: true
  dbCredentialsSecretName: go-ride/staging/db-credentials
  jwtSecretName: go-ride/staging/jwt
